name: DailyUpdate
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Script
        run: python3 update.py

      - name: Save Results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sub.txt
          git commit -m "Auto-update: $(date)" || echo "No changes to commit"
          git push origin main || git push --force origin main
